apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnc-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: apps/cnc-staging/manifests
  destination:
    name: cnc-staging
    namespace: cnc-staging
  syncPolicy:
    automated: {selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true, RespectIgnoreDifferences=true]
  ignoreDifferences:
    - kind: Secret
      jsonPointers: [/data]
