apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kali-root
  namespace: kali-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gpu-local
  resources:
    requests:
      storage: 50Gi
