apiVersion: v1
data:
    password: ENC[AES256_GCM,data:SP8E6hUeQ0wAaXmN4a78T4QgrosaHIdGrRSVKdOlb5RMxedVD7kApkKnWKE=,iv:SlWJLJmsYnrj3fPQHs+sqDznlBB/okjtOk8OnGGAFe8=,tag:qQ6/Cflf3lwNDQdmYBlOHQ==,type:str]
kind: Secret
metadata:
    name: awx-admin-password
    namespace: awx
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOTFlSFJaZ0dIeVdrd1Q1
            K2dPenhrQ0VpNU5QVzkrUDRCSWxzU0o4M0QwCnBLZW1rVmE2Y1ZqdEs4V2o0NXhu
            L09LbVBvZzhTc3lTT1ZSMDIxMnpaUW8KLS0tIDdEWUJZUVJkZ0NXeCszOXVPbGhV
            NXh1a2ZTRU1HNThVd2R2SEwyRlBabFkKqgQQAwdBb1a26rSv1oUK65Yq6rhI3ITZ
            bNodVSh0LhY8XTJ0kpfL81YZ4W0Gj0Peo2x4VfwfqwvpPzO4GsjX0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T18:16:23Z"
    mac: ENC[AES256_GCM,data:6Hph11V19uNDSsqGR2XW1Rum8iY8HkdU4/E7EsVJ/F5PC1Q2eYkbbfM+DKkhcCaew+TcAx0g3lTOxLAgzPClK+Iv8yKE7+HF866URS+8pXjOFQO87gge6Ua4jCid9X24jM4IfX+wPUsf+A32TgDaLZogqoD1z/zaIEh6Bv+dThQ=,iv:vCNuu1bF1l1ALRFLw3+Uyqho83BaoiCIzlsIdWgJCxI=,tag:sfdOujrymwgkCLjuMVFJAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
