apiVersion: v1
data:
    secret_key: ENC[AES256_GCM,data:ZudnkXRMDIrp0tAoRIMVJCQC4JQlE7UgOcOy5gOmjrUWovYGooW1nmiohH6qXjxlvtIpqvTffQuOZC2JyY3DxPGxZLD9P+kwtdV1yjo3RGd+CvHN4pIRwQ==,iv:c9494d36RiuJmi/UelamFr4mAB+P1NHOdAGHtnTn7hU=,tag:QtHYzj3+jW3W7W2kxW+anw==,type:str]
kind: Secret
metadata:
    name: awx-secret-key
    namespace: awx
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM1BiWVIvdFAxRDR5Rm9J
            SzVFdGxVcklJZmVUWllnanNOZTVSTFZkdnhFClRtRVc0L3RXRWFsN2ZvRml3V2xW
            Lzh3T1Vwa3ZXU041UDlObWl6cmdncFkKLS0tIHhjS1BMNjUxM24wVklacSsrT0tD
            OVRrOHdSbzNUbTZMQk04OUpocTRIVTAKcxPL2t5BetGhxmOlimgEbp9JMvDMwaY2
            AZoJ/sr0ln7XQ2nwGQjuGm5igzK2rAvX7DN47kUBXSIfKhTVFLzOug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T18:16:34Z"
    mac: ENC[AES256_GCM,data:hnXJMXucFWwd6ZrjyVXmF0bPB9hXH/KKy2wYyg1Xg1MATizQBUm3pBE3FGEqGe/u0hZTymSUIcBHgoi269oiJxpCiuKJ2MDuqHluFUU5p9HEknDWInI45sTH1Ldw/sAbhtM3cgViRXRdhDSsYUl9USJKnahLF+rnWxozmFRJozc=,iv:cFAq/IZ+xa6HcjPGfdIn1wH8TWKgG6mwzJEZaefynIA=,tag:WDnjPlj4cBBZ2p3kDIgEgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
