apiVersion: v1
data:
    authorized_keys: ENC[AES256_GCM,data:7vKCLPFOFTwX/c59Khc7u/01CP9CmyUclnxdbED+DfUE2tg7SGy0IQV/FEEWeuUUwR50ROoMoh+0Q4Ks2eyFXcQI7lzqZQ1OGn/3LFT3xNaiDR87u2daLrA++x/9bOJYBrTO4eeWyHpDhWnt2oqITNNRSE5iXb3J7d8fn11toQeDQX12naduH7wtLGCwFoDeSyGUfi5CnSPZ1xKm5AmBEMiMbVlOOTMwu2BaQsZMH7eKGG5c7KloCFhbr9iGlVpKflgmNdty+8q8H4gU1SMqY7s6BAQhnItEpMoYtpwwTXFyo2WjLN+ez9BHAE1stmjC9zK+OEJDXJiJHVvC9s1+LAG0FhRhq6lsw2TLenQozy7HGfQMyV2trs/SMIXwks7oeByQP7UJ4wFeXM1DJxi4Ll1YS9UahGCO8uRUPXy1WowUTmrjI+bJ6HIo+sm8uIzcRM6d1SjCNAal+Jofg7wrkef9A2fhCGeKkc+yIHVdb6QvWE0XgpH+HIhMrejzb4ksPJpfH7h98Bq/pmA/InISHVo2uaYOzvKGMC3PfcI/ooHDqkeB6ivf5O4o3vVLbW0Ahhko9Nv2U6o6m4ZJuVlHfoq+59X9A5tenzlwGCgOlBDeAFynXBw8fzyZC2fYNy4yHrcJQTnYbRC7np5c5vHsR32F1/3WhpukPUfnka+37WIkpJQzHmvjJyb314cLJAbHfOmmwHvAE2L7WIT23m6FNivVtkKziULgtgdDMIsvM9kOQV27ckmI2gFRG3oJJFz0ce61Ip1SQRheIQQCDWdJ44LbP2YLE+ekYR/JzjJbLSrLC8TBJy3HTU0G9FTq97Sjmc4JyHf50TVwr+lsz3AKmzWuN0g/zglHuGUfXPdTdbJ5iHqztMB4OOk82C3Zyqei/GEIQtZx5GKu4WjEPjBSI7EvjtIjzLVNqTz1UtS9U6Ll5sKlckncyJSn0RyrngqCORJJTF7e6OS0glTYl51RonG01pJyBJ4kps3VVEID0zsdg8FcuxOjOsBw3VeUINDMuikEy7777Gy+/z32Y6eexfbxlGvlzzBZgfZpIaI3ADoLff4/3D10gxw3OLdF8D+50KjGRy8ZrdubOW890B1fvmCVpKqkkdgsCqpIe488pNtlNlov+/Z44uYT7ejrJ0Sl4uW/SEGN9DVU3hL/YnH2nMZLKn+fCMOKNvZp69vHJrb9BUnsanrw/tXeOsrdikOAdmDJX9sKBJu1CxCG6eKD9CcMTECmnoF5WNCJTVSJsX8KVTalMYSeuc7+9PSONepDJ2CUbTxfHLf1Hs1yU/jww/TSxkZzPzm/8+LlVcdpTaf0A4Ck,iv:fJi0JDdlxO53RgOymUXPS1ovqweiymKHiJ1bGCFEhl0=,tag:S29MNjnDsNS3tFT6ZmhNMQ==,type:str]
kind: Secret
metadata:
    name: hermes-agent-shell-ssh-keys
    namespace: hermes-agent-shell
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucjNQWVIxeDJQMEtaSmZP
            UXBjMXRyOVNnbFhQMWRQQkZpaUJ4SUZjNjI0ClUxdm11UVVDc05DQ3doZXkyRDVy
            dXRrRWRCSndIRFJ1MUloVEZGOHdycjgKLS0tIGRWQjd3SERuenpIVFc1OXFxUWkw
            ajA3L0wvQ2R2c2VhUGJMV3ZabHFwNGcKmF0WRxItqUSDP7wei+6tGfMHqx0ecTpB
            iRaGtdDZ4C8QDgsrRYjBmVhWTHTWIG+uvtinTo8WoxmuoC4ho0mT9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T16:06:50Z"
    mac: ENC[AES256_GCM,data:B14MHAVb3Z60eTmJJY0wl4dB0ssbK2MQxKVImM6l0cxK6I1PUBgTmQCI17fCQ/PMSoRQZD8OpGcP7uWSyq8pWSZ9VyI2sgiOH+JYuRYQb4sBQpqA2a39MMaYbyLBIU3jRrijI4kgCOoIJlzU8R60uQYaheo3D0RrkSZxbH5DWgQ=,iv:DjWCrYfv1KQasfzEgT8VIuWyaHUEq7gDLEyM8VndWLI=,tag:js5dK/IoaAUqxMpVmZ7MbA==,type:str]
    version: 3.13.1
