apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://frank-longhorn-backups@auto/"
  credentialSecret: "longhorn-r2-secret"
  pollInterval: "5m"
