#!/usr/bin/env python3
"""Generate a blog's data/layer_palette.yaml from its .blog-craft.yaml layer registry.

Reads `series_index.layers` (a list of {code, name}) and emits
`layers: { <code>: { name, light, dark, lt, dt } }` — the single source of truth for
per-layer colours used by the series-index cards and the roadmap shortcode.

Colours are built in OKLCH: one unique hue per layer, a hue-dependent lightness that
tracks each hue's chroma peak (so yellows/greens read vivid, not muddy olive), hues
assigned in a permuted order so successive layers contrast strongly (not a rainbow),
and a per-badge text colour (dark on light swatches, white on dark) for legibility.

Usage:  python tools/gen-layer-palette.py --config <.blog-craft.yaml>  > data/layer_palette.yaml
"""
import argparse
import math
import sys

import yaml

HUE_OFFSET = 24.0
CHROMA = 0.20  # requested; clamped into sRGB gamut per hue

# lightness at which each hue reaches peak chroma in sRGB (control points, 30 deg)
_PEAK = [(0, 0.63), (30, 0.70), (60, 0.80), (90, 0.85), (120, 0.74), (150, 0.70),
         (180, 0.75), (210, 0.62), (240, 0.48), (270, 0.52), (300, 0.58), (330, 0.60), (360, 0.63)]


def _peak_L(h):
    h %= 360
    for (h0, l0), (h1, l1) in zip(_PEAK, _PEAK[1:]):
        if h0 <= h <= h1:
            t = (h - h0) / (h1 - h0)
            return l0 + t * (l1 - l0)
    return 0.6


def _lin2srgb(c):
    c = max(0.0, min(1.0, c))
    return 1.055 * (c ** (1 / 2.4)) - 0.055 if c > 0.0031308 else 12.92 * c


def _oklch_linear(L, C, H):
    h = math.radians(H)
    a, b = C * math.cos(h), C * math.sin(h)
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    return (4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
            -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
            -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s)


def _hex(L, C, H):
    while C > 0:  # clamp chroma into sRGB gamut
        rgb = _oklch_linear(L, C, H)
        if all(-1e-3 <= c <= 1 + 1e-3 for c in rgb):
            break
        C -= 0.004
    rgb = _oklch_linear(L, C, H)
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(_lin2srgb(c) * 255))) for c in rgb)


def _text(L):
    return "#1a1a2e" if L > 0.60 else "#ffffff"


def _perm_step(n):
    """A step coprime to n, ~golden-angle, so successive registry layers contrast."""
    if n < 3:
        return 1
    step = max(1, round(n / 2.618))  # golden-ratio conjugate ~ 0.382
    while math.gcd(step, n) != 1:
        step += 1
        if step >= n:
            return 1
    return step


def build(registry):
    """registry: list of {code, name} -> ordered dict code -> {name, light, dark, lt, dt}."""
    codes = [r["code"] for r in registry]
    names = {r["code"]: r["name"] for r in registry}
    n = len(codes)
    if n == 0:
        return {}
    hue_step = 360.0 / n
    step = _perm_step(n)
    out = {}
    for i, code in enumerate(codes):
        slot = (i * step) % n
        hue = (HUE_OFFSET + slot * hue_step) % 360
        pL = _peak_L(hue)
        light_L = max(0.52, min(pL - 0.02, 0.70))
        dark_L = max(0.70, min(pL + 0.06, 0.86))
        out[code] = {
            "name": names[code],
            "light": _hex(light_L, CHROMA, hue), "dark": _hex(dark_L, CHROMA, hue),
            "lt": _text(light_L), "dt": _text(dark_L),
        }
    return out


def render(palette):
    lines = [
        "# GENERATED by tools/gen-layer-palette.py from .blog-craft.yaml series_index.layers.",
        "# Single source of truth for per-layer colours (series-index cards + roadmap).",
        "# Edit the registry + regenerate; do not hand-edit.",
        "layers:",
    ]
    for code, e in palette.items():
        lines.append(
            f'  {code}: {{ name: "{e["name"]}", light: "{e["light"]}", dark: "{e["dark"]}", '
            f'lt: "{e["lt"]}", dt: "{e["dt"]}" }}'
        )
    return "\n".join(lines) + "\n"


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True, help="path to .blog-craft.yaml")
    args = ap.parse_args(argv)
    with open(args.config) as f:
        cfg = yaml.safe_load(f) or {}
    registry = ((cfg.get("series_index") or {}).get("layers")) or []
    sys.stdout.write(render(build(registry)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
