apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
  namespace: headscale-system
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 3000

    headscale:
      url: "http://headscale.headscale-system.svc:8080"
      config_path: "/etc/headscale/config.yaml"

    integration:
      kubernetes:
        enabled: true
        validate_manifest: false
        pod_name: "headscale"
