apiVersion: v1
kind: Secret
metadata:
    name: agent-secrets-tier2
    namespace: secure-agent-pod
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:zgGuw6dXz7j40QiCRMX2dw+DApsAnt/i+ai+HqCRPHMJLm/rCO0nqg==,iv:YOC37vJ396fO8l+MUbDvpOWApBdNzt0B920u7RRdovg=,tag:r4WRH3bVpVL5GgZeQPrixg==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZXdxS1NaZXZWQndTV2Ns
            dk5xQm5CWlNmS01XVFAySm1GeERtYk9Zdkg4CitHRHF1R1FhZkdiWDFrblRnNEZv
            cE9ZWXFOb0lPTTFmZExtd1hXVlZiNjgKLS0tIG44SXJxNmtxcVJoMFNDMTNRVTgy
            K2QvazF4UmptZmxSeklFT1dEY0lEb0EKJA3meEvFRWmAQnCB16Kefr45UdrpfTyP
            35aEQAEQ//NtfHPJCrKOai8lfs2tJamp1pBXqFv4wpjedKV93+N+LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T03:09:16Z"
    mac: ENC[AES256_GCM,data:FeWTlXi1ng5DK33BY1MFC84Syx8+jEgUH2UK7TWgr2KtehjWwCQX85KF8RHcGQpXc67oMEnFM36NZxiJPLR3O4AUheFEjuGXae1Ea8L7NaKFr1q69s6TBXkBVOBKDW8iBh0n53ob2jWQg3WbrmXC8mSjWIdoemKNCmGU8cZTde4=,iv:YzwaCXcAnbycJVLFqUWDh+4IS2pSk7Bhsd7MmkiyzaU=,tag:3V+tiewlBSr/0N6UoFZ9lQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
