apiVersion: v1
kind: Secret
metadata:
    name: vibekanban-secrets
    namespace: secure-agent-pod
type: Opaque
stringData:
    VIBEKANBAN_REMOTE_JWT_SECRET: ENC[AES256_GCM,data:9s1Gbtvt/sh9FbAib8mloBCqUoloas6cLJb1OMS+AZNhPz6W+Tjfbbz8G91vlUmHZlIg0Cc9fmNssZ2cUbwEHQ==,iv:4ADLn7+6h1Zs2BqY2mfMM4ERFbwVFP/kY6BsUzkUE7Y=,tag:fqLjNgKqcQb1rsD1D3O9zw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ef09CrSTNvpuMqTDdmDcBg1DxLkJBidJhd1Ej/GJnVWyShofW5JONNhFMRc=,iv:f+8SNnFapQgNMrhfCdI4df9CazeGhINHCzwTXIUMNGI=,tag:rTxGUKU9CPDQEm+/5PZP4Q==,type:str]
    ELECTRIC_ROLE_PASSWORD: ENC[AES256_GCM,data:NiAR0SEQU80T5lYPGwjJXByNLjEULBXAPcMP2b+oHMsheWfwY4icBHRjDVo=,iv:ub5LD0GPHwKDaBO41fF3WVnk7TC+HLmAtoH6R9PiOMs=,tag:1mIB+grtDxDYDQECctj74g==,type:str]
    SELF_HOST_LOCAL_AUTH_EMAIL: ENC[AES256_GCM,data:o6glay162fE2do3vsEgCyxeE0Ygwtfev,iv:4om/+MHjp2pgKczqBIWpp8UQPCIS85YC1taZ6mc1jPg=,tag:Z16o3bFqsHVkyLLwMx22gQ==,type:str]
    SELF_HOST_LOCAL_AUTH_PASSWORD: ENC[AES256_GCM,data:czsrYaF3SQDbm9OZ03AH8loIQiOO+ULIpafgBu8SUCfWaLPclaCw2TxH7r8=,iv:6Y100UQU2i8o0uuGqZr53bKzi2BaZcM6h2+HvhV5T2c=,tag:6Pi4tbedO0pIHJJkyslcRQ==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK2VJTGNMYkM1QWl3UDhm
            M0FHMlJkWWxXZlN5aVBDRlNiOWJ1cHR4L2lFCjFZWGxkN0tnbFJNcGRTNG96NXht
            VFNzSFF0OWRkUDBKRjgveTdtYUlNTDAKLS0tIE1XczBKbnZZZHdzMTRvcU5pRnRj
            N2luam5IaCsvZHVpazBkNzF2aFBnMVEK5R8BlO4xlZh9rFJn6b5FfBDZtnTUIzhj
            ZXTMXgZPac/rh/Fyxwb9Bp/ydUdPhZq5yNFsEw6krzR4kmsiqygvlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T02:48:08Z"
    mac: ENC[AES256_GCM,data:eFrjV+hSFP6OBNWrj9EWCQtfsYcw4MO+TL98dB3Ig8P/ni3srMQstmX7brBleACnfSgjoQp/ufJxu6WZ0vO5pNjxOS16gUNmMILsd9vVYXNcblGPLQoH/2PzxnFMV28o0BEp+lsFhU69Nsb7D8a1J5GIsAh00bJq/BVxFbVELiE=,iv:sVYI5UBez+FVYJys31wdu4kuk3B3GZqS6TJXtEsA5OA=,tag:2wFfYllrXpeJdETsue+tBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
