apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-webhook-secret
  namespace: tekton-pipelines
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: gitea-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: GITEA_WEBHOOK_SECRET
