"""Guard the kid-laptops PipelineRun contract and the generic-trigger exclusion.

`derio-homelab/kid-laptops` ships `ci/tekton/pipelinerun-example.yaml` as an
explicit contract, with a test on their side that fails if the example drifts
from their pipeline. This is the matching guard on Frank's side: what our
TriggerTemplate actually generates.

Two failure modes worth locking:

  - **Double-firing.** `gitea-listener`'s catch-all `gitea-push` trigger
    excludes only `agentic-stoa/`. A kid-laptops push therefore matches BOTH it
    and the dedicated trigger, creating two PipelineRuns per push — the second
    being the generic `gitea-ci` pipeline, which fails. The failing run looks
    unrelated to kid-laptops, so the cause is not obvious from the symptom.

  - **run-id collisions.** The request is explicit that two concurrent runs
    sharing a run-id create and destroy each other's VM. Tekton documents
    `$(uid)` as "a random value, just like the postfix generated by
    generateName" — random is not unique, so the short SHA is concatenated.
"""

from pathlib import Path

import yaml  # hard dep (pyproject) — a missing yaml must ERROR, not silently skip

REPO = Path(__file__).resolve().parents[2]
EL_GITEA = REPO / "apps/tekton/triggers/eventlistener.yaml"
CI_TRIGGERS = REPO / "apps/tekton/triggers/kid-laptops-ci.yaml"

EXCLUDED_PREFIXES = ("agentic-stoa/", "derio-homelab/")


def _docs(path: Path) -> list[dict]:
    assert path.exists(), f"missing manifest: {path.relative_to(REPO)}"
    return [d for d in yaml.safe_load_all(path.read_text()) if d]


def _one(path: Path, kind: str) -> dict:
    matches = [d for d in _docs(path) if d.get("kind") == kind]
    assert len(matches) == 1, f"expected one {kind} in {path.name}, got {len(matches)}"
    return matches[0]


def _trigger(name: str) -> dict:
    els = [d for d in _docs(EL_GITEA) if d.get("kind") == "EventListener"]
    triggers = [t for el in els for t in el["spec"]["triggers"]]
    matching = [t for t in triggers if t.get("name") == name]
    assert matching, f"no trigger named {name} on gitea-listener"
    return matching[0]


def test_generic_gitea_push_excludes_every_dedicated_repo_prefix() -> None:
    cel_filter = _trigger("gitea-push")["interceptors"][0]["params"][0]["value"]
    for prefix in EXCLUDED_PREFIXES:
        assert f"startsWith('{prefix}')" in cel_filter, (
            f"the generic gitea-push filter does not exclude {prefix!r}. Any repo "
            "with its own trigger must be subtracted here, or every push to it "
            "creates a second, failing gitea-ci PipelineRun."
        )


def test_kid_laptops_push_trigger_targets_only_that_repo() -> None:
    trigger = _trigger("kid-laptops-push")
    cel = trigger["interceptors"][0]["params"]
    cel_filter = next(p for p in cel if p["name"] == "filter")["value"]
    assert "derio-homelab/kid-laptops" in cel_filter
    assert "X-Gitea-Event" in cel_filter and "push" in cel_filter

    overlays = next(p for p in cel if p["name"] == "overlays")["value"]
    keys = {o["key"] for o in overlays}
    assert "short_sha" in keys, f"expected a short_sha overlay, got {keys}"


def test_pipelinerun_matches_the_kid_laptops_contract() -> None:
    template = _one(CI_TRIGGERS, "TriggerTemplate")
    runs = [
        r
        for r in template["spec"]["resourcetemplates"]
        if r.get("kind") == "PipelineRun"
    ]
    assert len(runs) == 1
    run = runs[0]

    assert run["metadata"]["namespace"] == "kid-laptops-ci"

    resolver = run["spec"]["pipelineRef"]
    assert resolver["resolver"] == "git", "the pipeline must be fetched at the tested commit"
    resolver_params = {p["name"]: p["value"] for p in resolver["params"]}
    assert resolver_params["pathInRepo"] == "ci/tekton/pipeline.yaml"
    assert "$(tt.params.revision)" in resolver_params["revision"], (
        "the resolver must fetch the pipeline at the pushed SHA, not at a branch"
    )

    params = {p["name"]: p["value"] for p in run["spec"]["params"]}
    assert {"repo-url", "revision", "run-id"} <= set(params)
    assert params["revision"] == "$(tt.params.revision)"

    run_id = params["run-id"]
    assert "$(uid)" in run_id, "run-id must include Tekton's per-event random postfix"
    assert "$(tt.params.short-sha)" in run_id, (
        "run-id must also carry the short SHA: $(uid) is documented as random, "
        "not unique, and a collision destroys another run's VM"
    )

    workspaces = {w["name"]: w for w in run["spec"]["workspaces"]}
    assert "source" in workspaces
    vct = workspaces["source"]["volumeClaimTemplate"]["spec"]
    assert vct["resources"]["requests"]["storage"] in ("2Gi", "4Gi")

    specs = {s["pipelineTaskName"]: s["serviceAccountName"] for s in run["spec"]["taskRunSpecs"]}
    assert specs == {
        "molecule-base": "kid-laptops-ci-kubevirt",
        "molecule-teardown": "kid-laptops-ci-kubevirt",
    }, f"the SA must be bound per-task so clone and lint stay unprivileged: {specs}"
