apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-secrets
  namespace: zot
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: zot-secrets
    creationPolicy: Owner
  data:
    - secretKey: push-password
      remoteRef:
        key: ZOT_PUSH_PASSWORD
    - secretKey: oidc-client-secret
      remoteRef:
        key: ZOT_OIDC_CLIENT_SECRET
