apiVersion: v1
kind: Secret
metadata:
    name: n8n-01-secrets
    namespace: n8n-01
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Xj4WNuj63Q3vKfApwXV+d8ytZ/B27QNsvPtZtIuekxo=,iv:G5hH+LESrRd1G38KsZUPLs/wokLL+9KbmjvlFwDw4vI=,tag:BemgzQ9lNSXEmFRt1LL7CA==,type:str]
    password: ENC[AES256_GCM,data:Zq+1htuHFTliswn/PJLozXA8MHSehSuqL5pFADhfmhE=,iv:f4A0NnMJZo/O/5SigTbCOle8mMIzO6sEr3WS4BwqsaE=,tag:mbrLIDCjLIXXR/DrkYmVOw==,type:str]
    encryption-key: ENC[AES256_GCM,data:fFqDM06vQGCO5YKCfguwIQT1tRJCNM/2uLu9K36jtyBloosqEBfSk73o2sIDYNbjTgdrCrW4SUVAehfAGZ/nWA==,iv:aqIuSupqfr295Ltcd+P/8Kt9J7BbYgqS69EJOvXSlSE=,tag:zjaCCJW3XWiO3WD5/yW+JQ==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eXM1TkdXdi9hZTIxZVRW
            RldzVXoreGNvdmNRMGpGRzZjWXlwQnAzWFFnCnBCdUlFUlNlUDdUT001LzkvNE1s
            dllvWHFJTnJTUGgreWhETVZiUmMwU1kKLS0tIC9xRDZEdnF1MEJRUVB2dW0ycHVh
            aU8zMWQvUEQxN01oUjliNUFRQWNLYmcKbFnCvVUPENOmhAqgOiHFOJC4+1jQfrEC
            h9Suwaepqx0dYx9PUojURFQEs+sQmoZL0IfAxvu18ysGlYbBwv4YDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T20:54:54Z"
    mac: ENC[AES256_GCM,data:K/na2AdSvLFkGPkekzAvAR2hZq8ArtQdhMypXwT/9S3bI8877fsUmVtnSO4oa9fo1FJtKyYk+JrVtwa6XxfJxNrW+XfGcr/YGbrcHC5xAAk0tg3uwgyng67b2ylDawh5BUt/RXgrKdBYXbEWCe0nuuHNWZ676Q1QyCoI2PoEoB4=,iv:oK5W+42qL1NtlWQyXl93XzsPpyEb2nZfnR+ep8T3wpc=,tag:Ddo/6fodJOiL+qoL3yXWHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
