apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:NAg4pE0wWBknPxbZlLD84x5VuTHSnuXFsbZaXxfREZYJG2nSX41paQfoy2Bj+bARgSY=,iv:UiM/faYe6uJ3IhVU0dBArv9M7ffnsEndIza2KbyJvps=,tag:ccKzjgAL/SPcXhp0IlTbSQ==,type:str]
    postgresql_password: ENC[AES256_GCM,data:6oNjE3+wcPBkPCvtOw7EEwSpgKBhOoBubkKUjFSfNlY=,iv:ypL+k/b5fMpXJtJLxCbGL7W00HKx9Tl/qF9/fc7CFGQ=,tag:g1vIGUt1xUC/Uk2Zd+CIsA==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:PeroejeACT6nG8chdOWerGEvp8TRabJ9up4H3DAh6Bw=,iv:5XYYC1qVpj40vj13oM8Am8BzJ3UmsV9hV4JQhvD1DpE=,tag:ARSwwLTfdJ6lPY+RP6rf9Q==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdVJ6dGFvaGREMkVaMWhM
            NVRsL0llbDVabmlQdjNmMGs3NFNpcS94a3owCkRlOEtjcHZ6TDdmV1gvYTBLdVRw
            emxUbDJhVk1MUTF5N3Jqb3VvNjdIaDAKLS0tIDRSVTJ4YTlNSEYxYWZOY2J2S1l6
            UXpCQ01jTkZmNW14OGhaVDJMbGRZWkEK6OoQotkG6JtToJuubKU4cz0pcD1e5Iis
            WItleseHpzXf9FWcgp2tp+oMGP6JCPDjMgMTWEZXvm0ndu8XKR5uVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:53:35Z"
    mac: ENC[AES256_GCM,data:89p1NmZB0YXoAQ5m0LDGIzhUF4nVQ/nRPxxRnw4PbffosQH/H5tlpkSxNZ/QXDj2M4GEEuNUFXRFQOpFH2o34Oe/l79PeBG+WaLjA2+7ZK2rjnvqQReN4zrrDMEkhph+1+PAQq93fGxt4OZS9FX8lT4Bg1mAITvZlPPjp/tHRr8=,iv:MgMZfqz0lrBWhG5fT7eu1FC7NlHquNRhn45uaPnUKFI=,tag:daVJiWdKg+0Q7iEZUlZfag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
