apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:98yQ3LKlcE/Xjj9KVX7dQqeYBJcxuuk+DM+g1WWRK3E=,iv:2a437QTexTTu8Pu45PyDXXJdHhiSM6SlelKxiqgNnvw=,tag:1ElYp4m6HS6+vy4ro2n/rA==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY2huS3Flc1ZrVzVyWEhm
            ME4vMGNHZnZlaWtHWDlGUk9tZHUxLzZobG1ZCjdSV0NDclJ6NDFTdVN6RGNVTGk4
            VnJwREVuRkp6UG9nNTZmQkpCcVA2ejQKLS0tIEJoUDF1Qy9PYTdLV0NoVUN4YTk2
            WDJ2OXdacmRFakpoSUo4U1F2NnkzWjAKlP6qSW/QCOCB/BiHVVoWcr1RujzY3pHv
            /j2x3G/GSdb3yCAycrUL/dzRdFvq+L9yyYOmHUDOGSwIPiI3LMiDPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T21:25:02Z"
    mac: ENC[AES256_GCM,data:a2tkA4a6UWMgoC7Fe8IA0fMJS6zJy9Xa4BTN5TvjqwdSWh6ohksCUyz58ygC8M0I1NSkamCqWcW21bM17iY6fo2l9aaVXKgH2LYT14ESbWmnD7lWpMC5gQrDNoM66Gd2NtOtIYRrZ4mDcoug8/021qntIE03Yem+B6hQRM1bjv0=,iv:3li50QhRnoHQq8gWSkud0EnEnmCoJKM024BF+RkPQmo=,tag:e0okTs8ZsVjeZqJ3UjqhHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
