apiVersion: v1
kind: Secret
metadata:
    name: infisical-oidc-secret
    namespace: infisical
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:2UMSdLwR5Lp/1YwF9fWRsHYjcrPFftaQbzRg3zlSBaY=,iv:BverR2wENr2sDLG3HAPMI3RENfCMA8rESJyKRdoNZ90=,tag:fG3B6JlWxrw2DPYaZYQNHw==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dDJGbFBmd3N3MGZyKzFH
            MHR0MXQzRWY1SEZEOVFCMG1jenM1c3VZa1ZjCnRMSWpwenFKcHltb2t2N3dMS0NP
            K0hNRndxMDRKNmQwZUp1aU9LbEtDQUUKLS0tIFpOTjRBMGI5Z3R0eGxjOGxSeW1j
            eGpnZWxYZk1ub0JIQmpRZi9xdHVhSjgK/o94z3ER+q+YUbmb3hrbL0n7KwImT+Mu
            U766/GkouqP8s1NkNW5EYfZoofNx/u3hcxrasx6FCyLk4oJjFFzr5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T21:25:56Z"
    mac: ENC[AES256_GCM,data:JKLSt48v/odroIliVPH1jIxZkr69ndX2HznMvjIeyxIzAYMLCMVVC4Sogu0pM3bWY6T+20+fAc2coPZyrEj4UVxItZphnSXv5IWSxPUFYnc/qbV0soTi/fLE7yVuMA72X4hrwrdOfaaF2LiUbWUjLjBgVkp5OrdtnXAtFL4HX+I=,iv:DpvCqhiENVhFFGEUqE2umwcc3WbMVILiciV6mXbHXXk=,tag:3eWXELFCIy4cWVVgm0OMGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
