apiVersion: v1
data:
    authorized_keys: ENC[AES256_GCM,data:LUVe3xoDcpaqGum00gfVAfp6aE/rg6sBVE/T+kCt/W96XQ0UDFnSGHh/eF0m/q1iWmYSaf4HRb0PbVCmGCx0zHxhG/lvPIJKbaexlM2aKAb0skruccHgvKhmnkxQcrmvG0UBWKum9rLBw5ZvXVQfBiSL9AXPilrSD4LpLsp0zuCtfR5/gMO4mw9GziQAdlStBARYnCd7HLKFXBjaWGIdpugrvIS8irDmKfMSUwR3ze2ZPafnduYv6/Gbolj9LcVgJIZdI7D30c8Q8kth0biQsDYzOb1tkRhro3+v6zDc8YLmy9uHgv0IL63sMfNsd1XCBY5WQer65AmeIDroFz/DlESaHWQOM5ajtTz8NTPyes60bjaPNDXzKNZgPPor8vx0r9kmouzVWUNDHQ1lhuD4hBKYeLS+kWs1qbbTxDTU/qjyWiAQyxJNlyXBXQXYPrtRkM8k767BtzLmwMYNJaDh5m1DHvP29uM1AxbDcGxAQkFfFjf3j4nfMa6m7ts1y5tEF7JaRYDwkLhL1u41OK6Fr6Z7T9cMrCOlzhpSvhyPkMeku+MGT5Az5ni6T6ak+qE24JDTclUAnlFarM0mNwH1EvuLeJvAlJylAN2esjDpoCImqidti5WLmyDXygjdnKC8FnuozkVZf0pX9GgfWn6UotjughgsGG/UezzDxS6hJ3xDROCn18t6R18gZJn/AciXeeoT1nPONyT5fIInVfPL3EfFMzRLM5Gy+sbEJh9gWu5YvmVdh1fl3TeGF1fiqaPvuebXMmzj0xj3/35QSeQFW70kMLAAlY2j0UtRV2NNlnY5/ITMYqao5jNESnMCIAgprqVDGKgVCxdEXUojLmYFfOWgjsUtd+qBrghgZR8v1BmF7fdJsG8lb9Aki8q0Cjd2ZTnondRaopL47QXoRW33nN1QSrfeii8XBLMchtaqs+wTrW5s4cbHlw/gafcRLj5tFDAOu+zOlQYWylQE8IBkba96PkvPnstRkCS+oZe1TzQPT4OkWpMz1k6lsT1Kpm89h99FnB0Gd45tD+sw7f8yqRrwJ5gpwJxi3rzVrGjwA7UADSkUH5HDmAuqi6LOoXRlJ7OaraqrQfTwbY8EfQEZeb6U/2jt1sntnKH9J3vS1mKT8fE261ECZwRtKhQGsFwNrUi0lO59bfCMJtHlRJZ8khbSRhV4xcDefhXFMc1oYs38uYWY0o6IIrRFv3fhaRTNlg+jHdyFyuMSI2UHMs6va9Ioy07AwBEeTUY3cSOb8jz0HadAQyNqkPSoQ0a3FWGrZhMBBNdMcUKqZZOVZYxkiMTfWZVx6K80xTQSa6zWFE2ZaFsm,iv:MG3pxcNz2R3qIoyyzY+FV8AkpD0XMAwFkLmjpgIyPyU=,tag:2uwMf+wQjnZXUZNW/JyREQ==,type:str]
kind: Secret
metadata:
    name: ruflo-shell-ssh-keys
    namespace: ruflo-system
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1R3TktxN2Zzck1tNktI
            QlZ2UFh0bTFZamJwcWljL1hkb3FZZGhlNlI4CnBtNENLMWJ2NmhzMW1JOXQ4NVJN
            OUtEMFpSSVFKQjU2RXl2NzJwa2ROWWsKLS0tIGRvQlloeXhPMURVVXRkb0VhY2dH
            UXNLbWluc3BqTlpNLzJBMmN3TkN4bUEKRTb7O8RDCKkJChBzURXsfQK2dTYs/Cf3
            8mcvAGAeu/Zxn9wWdC6DZkRDPglgfNpmLQfmtEzzV2RlcW/R6r5s9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T08:44:14Z"
    mac: ENC[AES256_GCM,data:mZxKG3PPhR6BJC9HmsH9ODDBfESLFu52QR1e21LAEV/FMkCGIeIvn5ktiDCUs9jiG8EIs54Pfze4ZtsBn4eN8P+YjiFKZSAcxYWO8k8ZK/BhYwiNz2G2pJtYQ9lgCTB6uDHSelKlewL0b8tpuAFes4Ujh04K8MqNPVmzxZEYbeQ=,iv:A8qAaQ0rI31Jlb7hv0pcqzVqlMxjmQEaOMInXXZ0p3o=,tag:bJ/zMe7+qignYsZrHkxP9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
