apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hetzner-volume
  resources:
    requests:
      storage: 2Gi
  volumeName: headscale-data
