#!/usr/bin/env python3
"""Generate blog/data/layer_palette.yaml — the single source of truth for per-layer
colours used by the series-index, roadmap, and papers-roadmap shortcodes.

Design goals:
  * One unique colour per layer (21 codes from docs/layers.yaml), never reused.
  * Vibrant in both light (#f8f9fa card) and dark (#1a1a2e card) — colours are built
    in OKLCH with a hue-dependent lightness that tracks each hue's chroma peak, so
    yellows/greens read vivid instead of muddy olive.
  * MAX contrast between successive layers (the opposite of a rainbow): hues are the
    21 evenly-spaced slots, but assigned to layers in a permuted order (PERM_STEP,
    coprime to 21) so layer i and i+1 sit ~137 deg apart on the wheel.
  * Each colour carries its own badge text colour (dark on light swatches, white on
    dark ones) so the number badge stays legible.

Two aliases (`inference`->infer, `docs`->repo) mirror the keys roadmap.yaml /
papers.yaml happen to use.

Usage:  python blog/scripts/gen-layer-palette.py > blog/data/layer_palette.yaml
"""
import math

ORDER = ["hw", "os", "net", "stor", "gpu", "gitops", "fun", "obs", "backup", "secrets",
         "infer", "agents", "auth", "tenant", "orch", "media", "edge", "deploy", "cicd",
         "auto", "repo"]
ALIASES = {"inference": "infer", "docs": "repo"}
N = len(ORDER)
HUE_STEP = 360.0 / N
HUE_OFFSET = 24.0
PERM_STEP = 8          # coprime to 21 -> full permutation, ~137 deg successive jump
CHROMA = 0.20          # requested; clamped into sRGB gamut per hue

# lightness at which each hue reaches peak chroma in sRGB (control points, 30 deg)
_PEAK = [(0, 0.63), (30, 0.70), (60, 0.80), (90, 0.85), (120, 0.74), (150, 0.70),
         (180, 0.75), (210, 0.62), (240, 0.48), (270, 0.52), (300, 0.58), (330, 0.60), (360, 0.63)]


def _peak_L(h):
    h %= 360
    for (h0, l0), (h1, l1) in zip(_PEAK, _PEAK[1:]):
        if h0 <= h <= h1:
            t = (h - h0) / (h1 - h0)
            return l0 + t * (l1 - l0)
    return 0.6


def _lin2srgb(c):
    c = max(0.0, min(1.0, c))
    return 1.055 * (c ** (1 / 2.4)) - 0.055 if c > 0.0031308 else 12.92 * c


def _oklch_linear(L, C, H):
    h = math.radians(H)
    a, b = C * math.cos(h), C * math.sin(h)
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    return (4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
            -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
            -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s)


def _hex(L, C, H):
    while C > 0:
        rgb = _oklch_linear(L, C, H)
        if all(-1e-3 <= c <= 1 + 1e-3 for c in rgb):
            break
        C -= 0.004
    rgb = _oklch_linear(L, C, H)
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(_lin2srgb(c) * 255))) for c in rgb)


def _text(L):
    return "#1a1a2e" if L > 0.60 else "#ffffff"


def colour(hue):
    pL = _peak_L(hue)
    Ll = max(0.52, min(pL - 0.02, 0.70))   # light mode: vivid, not pale on white
    Ld = max(0.70, min(pL + 0.06, 0.86))   # dark mode: brighter for the dark card
    return {"light": _hex(Ll, CHROMA, hue), "dark": _hex(Ld, CHROMA, hue),
            "lt": _text(Ll), "dt": _text(Ld)}


def main():
    print("# Single source of truth for per-layer colours across ALL layer-coded shortcodes")
    print("# (series-index, roadmap, papers-roadmap). One unique colour per layer — never reused.")
    print("#")
    print("# 21 hues, hue-dependent lightness (OKLCH, tracks each hue's chroma peak so no muddy")
    print("# olives), assigned in a PERMUTED order so successive layers contrast ~137 deg (not a")
    print("# rainbow). light/dark = card variants; lt/dt = badge text colour for legibility.")
    print("# GENERATED by blog/scripts/gen-layer-palette.py — edit there, not here.")
    print("layers:")
    colours = {}
    for i, code in enumerate(ORDER):
        slot = (i * PERM_STEP) % N
        hue = (HUE_OFFSET + slot * HUE_STEP) % 360
        c = colour(hue)
        colours[code] = c
        print(f'  {code}: {{ light: "{c["light"]}", dark: "{c["dark"]}", lt: "{c["lt"]}", dt: "{c["dt"]}" }}')
    print("  # aliases used by roadmap.yaml / papers.yaml")
    for alias, target in ALIASES.items():
        c = colours[target]
        print(f'  {alias}: {{ light: "{c["light"]}", dark: "{c["dark"]}", lt: "{c["lt"]}", dt: "{c["dt"]}" }}  # = {target}')


if __name__ == "__main__":
    main()
