apiVersion: v1
data:
    authorized_keys: ENC[AES256_GCM,data:b9Svps9IJVheZKhZADYNaam9/GSDf2+1jsSoVHsjpY1p/oOzdWSDjds56Olv1wMo6fbqUG82Ao9fg56+1l9wS96TLfUrkZF+6rYh3r4tBFQ9/t5RyvZTnO0vGJpF0+Zb1mGtd0j1xCNw9Q6u7z0gKw0oaLlco4fH4yStSjhR0YIe9dDhKlVBR8yTWLVo2TID/bnSCY5sfSCaifU8iBAFLpQGclcBTrDhGGmY8vKz56PaI3MNTMTsFpD23s+/KP0u49iPNiLCGNcrBh4FeW/mb2I0UB24WRmbVngx6rS7DXvX3fAwmjOv0z/E6oiFtsc7w+A6RnqqxR7zSXtSZu0wYqdnbpk2S2KP9+Li96B8J8MUinObdKNWII+bcuri95RDizXGJ0LALeKLjjseQyGWH0mtDx6m7gt/C2KHN9V2Bgxg0jjdie7Ohi20ITXut1JwY54ntucP6LKSdQbRFndGIZmOr4IdIGtM6SFoOmr4CckZDh8ynBksPlHIWRFTw9IAU+6kCbm5c8IQQ6U8mINnYn9CKs02nScCog+cpqfeCsF3NeGYsaGyrb6w4Vwr44aOWhh9FJVV6NfJybE9L39pZMq0KSYXzODHf9IpML9DrJiGMTtHYlH9ih+TenZoEJGkG+22ZZKFcR8B5oAQW/ogemhVQa51Vml89wn0H0AQm8+kt3V0WGIgmQog4gv3Pk1mmn/iRNkWCOb37gnPFJ1a5jLQWvL/UTavdfYYZpP1HszM2M2+tOVgMjVA3icL0IQT6IhtUVI0QAZWMJ3EN0RFlN+AkjLrbOzW2DiRQgMRqtsiX1HX8QQNbnunYM478FznYQQ+6vqQ2n7LDQvlbPZngDohhua14JwkG+6kz2V8p7H6QI03HUqRJ7D9RrTE7vBrbHEBB3cZRubTauLtwq2NAS7wswzu2SlD29fcgHvX3BIG7MGfLMP+reMYJ3Ns7KVYStXPyzE0Mp7NIbaBT5JPRLzovWMI67e7YZgjxgmOiPEXktM6TVBaycSMOnneBvdZtJ5yRlZpkE0cPalnG5sQxMvxhr9bwgT/iPYxoexXoub1ErAPkH67mOEgB1qCK+YpTwbTMdxp7cU54BV4k+rBpY54iBrW2IJpscxVB4ObjrXtBM8BElsB6MMuAFU7dCA5b2lZGJwraRqk8jVFtoUjXqg+z3G1t7trZgPcyrC8qpzLbKcA1xw2aZ4KArY8Ts4OqOKVL3Io5FzBwZhkahcHLJhm0WoaGMlH0FE1MITyqTVp377e3TgxizAuOQoch9CXmHHyB6dZEtWGSdG9QI5WLYUEFoTm9AABtJLKtc6YC9B63C5Q,iv:gcPNjEHJejgD9Nk8LN1KNf381ucuNqLHqqa4qh5BtiU=,tag:XA+4AMbr2NtvC52v9lAWxQ==,type:str]
kind: Secret
metadata:
    name: paperclip-shell-ssh-keys
    namespace: paperclip-system
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGJqdW91Z1c4L3V0QzZk
            YUM0bG41bE5waWpmZXoyaWcwblJCSnhvUlZBCkJFbmhtNnBBWWxFQkl5aVVFVGxl
            bkIrRnhDWTJlNHU1cTdQME9rK2RWR0kKLS0tIDdmWUg5WmFiZVJ1c0wyMHc0cE1K
            Mk1CWXVEbGM2NzBEZTV1ZWx6MXV4RzAKhyHpId2fPTTC28V+Fq/5bTvJIeLq68hv
            d3X4po/fXud4i0F4vSC6rpb5Uci9AlQQaJcZjZZolOr7ZTzWT6c81A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:52:51Z"
    mac: ENC[AES256_GCM,data:dyWPm37W/5AkWZCxrTuvADXUJGO5T4TbtnGfaOcTAgxe/u83l7XJjjVlqgTjYd3sUlr8X35X1ig9gfdu+puJX4hVveJlW/YJbgf1Ym3IEh1jCWneVhvMmbQ3axSMZDVpBkR6XkVHkzGlB3KyTo+QuD6lHqBRu26aoiQZ+yxQW6Y=,iv:Qh7n8EnL31FKL/bhILVBcggjHyZqe4FoqWXwEwLbTcc=,tag:NoYrxU+kv9XdaA9Y50Vxkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
