apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4iTrshvo21YK92L52Kl9VwoXcgAAjRfdkADm,iv:SiMaVY4wzo7hgaPXt8rALBca02cG6JregZJxFsI20kY=,tag:Htm4mfxz57tuGBVjLZvTFA==,type:comment]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:7DV51WbCrHYgmDtSVYSuN+2cWvAmvDFp/GR4Khpbkws=,iv:vG51ribIXb8JI7Yd8TXWNjMmfEoX21SB7aNSRx7gZpM=,tag:Ukh95AUHS/pzRr1B0Sq8RQ==,type:str]
    JWT_SIGNUP_SECRET: ENC[AES256_GCM,data:xiiItgxFxlpXN0T9w+vKROIvfJJI3xB8ng4YEnAN/uc=,iv:lGRpdowu3DfpBfovAOEcWrIX6t7HcU8gUb17Ps6P7Ms=,tag:fad6iO2CAJw112kbXmu13Q==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:JxT4hNLnWvaIueCLvue8VoZUXAnbF+wNSaGnmZfeDzU=,iv:W3/Ogo32ZZE3/qjAIbmaD0dBpX/c+RPsVcgeUo1owMM=,tag:EHdXKCifkFTuS+yccbUlcg==,type:str]
    JWT_AUTH_SECRET: ENC[AES256_GCM,data:4JCYNpLSkEse5qOzUan6X6nPLoQiiSrFM5QVnM0tskI=,iv:t3uZDXQjMNlI2JEAG80LxBgBr23X0f4kARO+sv39aY8=,tag:0OQGG4FGZedW/ra4tcYPew==,type:str]
    JWT_SERVICE_SECRET: ENC[AES256_GCM,data:BIY5MjVGeYPJOpbdv9LFsLxdxDgTUCFvW2pucvlJNM4=,iv:H756WFANu7zXAWllTVuP06CQvlMScjjwYLmKDTxSmfw=,tag:CdwEMc2ISFBoncHr7FRQJA==,type:str]
    JWT_MFA_SECRET: ENC[AES256_GCM,data:CVj6ZsyTvm7ya78mio/yeuwYaWF+8YE+ooFN+yflPAk=,iv:8nK/Y2ueNhYSkpljVcsHayECkJLreVcZg3otJPZiEGA=,tag:yb4ZgosIfJzlAVl/x0U0Rg==,type:str]
    JWT_PROVIDER_AUTH_SECRET: ENC[AES256_GCM,data:hyko1FgJsHvm38NneapHDwP010yFY6LmcPpp7I0xLf8=,iv:NrctJDc5Pp06jItg2Z6O6RFpUbJ9849CsufGRrcInOA=,tag:BZ2d6NqcmNaoVaMrmc9VjA==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:OdSRjGE8BqYMFEBXYTlIkcQiEeJ/tR1yb30cidSQ4559mCIfhaiJ3H/oIWRR8MTnUj9Z4chmkU8FSwziZqVTMqxQg1cQjUFNSqbB,iv:nooJYM/Yw+m0fFlEvi2B3uQU/6XyFiaGSPYgTk0FGfY=,tag:Y75WIjWFyEop3JMBlI9Hog==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:FNAmQ/Aoijw5ICcBdFzE86urEBLBEEPxHA==,iv:id48TDfGtIRkmsdjXFUaGGtugKJ2LyEQEPwOjrNJm7M=,tag:1vA/Myof/2NYXXFyJ5oE3g==,type:str]
    SITE_URL: ENC[AES256_GCM,data:g9IuKa6u65PyYqLwMojUhNyRJ+N5,iv:p9gCv1nDFm3i9iikqY5tsQGNORyAMNa9CGOLTAxyf2M=,tag:BXzcZ2AYcbx8VHXclEpinQ==,type:str]
    #ENC[AES256_GCM,data:EqsfO+XkS8NfXgtuvzy2TfWczqCQcTyrTF5xG9nCyiZ3M1Tv2aWBNwtyO0+kqQbZOQ==,iv:a9rCABP4+JBrwfKGS42AXrCKPcKRilNcTLHV5Rjdtm4=,tag:hf58S4fz+7n6fmU9AM74/A==,type:comment]
    mongodb-passwords: ENC[AES256_GCM,data:d8pJaVCPHu/dL4bKD3ok2pywC1iNC1Ce3ua3rWeVfw==,iv:K+7snioXTbmyAztZHYShhJ4bET9LTL2eVPIu6Q/N5K8=,tag:TxijzIM5zI+QMBwjHJrK4w==,type:str]
    mongodb-root-password: ENC[AES256_GCM,data:L2zfruhy1unJTbfPmLdHOSNhc8DNA4Tli6EpVfwzMw==,iv:fvbkWYlgwtsbGYbOt04wXXIXI6DmQtlo8FwBB8gwNLc=,tag:F7WpzucfzvC/V1aeJov4Mg==,type:str]
sops:
    age:
        - recipient: age1ufxvcn4us3cue5dglwn4uk8ctjfpuaw6dqlwu4hjzszf2g4htpcqkszjne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV2RibU0rUnN2b0wvNlg1
            MzA2UXNpTFJZVG10eE9pL0x5cXJ6bzdZclU0CjcwWW45VU1xcXFnNjFsYmtLclRO
            Slp6VzBoYmtHazZneHBpV1ZteHpqa2sKLS0tIFNaQWN2MmFmOU5KbWRFQ1hiT0VZ
            SHZueVhRemY2cmJ6cGhsU2VtaHRlT28KaPBVCGva4DAnXapdLmBmA3OdDNaUe+0O
            S/DSzgM6Dme1shFPfiM3wCatn/LMGBDg6gJw5m6HL99l5VYZtZ98sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T19:18:42Z"
    mac: ENC[AES256_GCM,data:lOC7+csklgbBCAUx+yRtZmH4bhdc/0RxsBXk6t9WCC/y4QoZHHwR7mv37OntTxMQQcASlq3O5ptafKfCimGCBU399M7/qwGtJ9i17cHNWxTNMvi/yrZLezQdGuprPyaJ+PSu8y+/Plb+FNqEMT/iYpod89Dew2kmSQ6ro35vtgE=,iv:USsu6DXZmqK+Xzt0IYB4pPZ9AfzbS2bsj5CSi/TvJy0=,tag:zJCzjhf8wqbso5O7NSAZ7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
